Create LICENSE file based on BSD license as per package.xml
ethz-asl/libnabo pull request #118
Opened 2021-12-16 19:16 UTC by Timple

Releasing a package as debian requires a LICENSE [these days](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-package-contents).

Created from the github template based on the license in the package.xml

2021-12-16 22:05 UTC, pomerlef commented
ok to test

2021-12-17 18:18 UTC, pomerlef requested changes
Update to the latest master

2021-12-20 18:32 UTC, stephanemagnenat commented
The license is wrong, the copyright is clearly not 2021 ASL, as Nabo was created far earlier and people from other institutions have also contributed. The best would be a date range and something like "the Nabo authors" regarding who owns the copyright.

2021-12-21 15:00 UTC, pomerlef approved these changes

2022-01-03 16:26 UTC, merged